### PR TITLE
fix: remove remote web url copy command

### PR DESCRIPTION
**Pull request by panekj**
- [ ] Added an entry to `CHANGELOG.md` if this change could be valuable to users

Git doesn't have any guarantees about web interface so the command should not be provided by Lapce

### CODE REVIEW

**Comment by dzhou121** [comment]
It doesn't always work but useful for Github, Gitlab etc?

**Comment by panekj** [comment]
> It doesn't always work but useful for Github, Gitlab etc?

Yes, but because of that I think it should not be available as built-in command in Lapce

**Comment by panekj** [comment]
Specifically, only GitHub and GitLab work because they accept URL of `scheme://host/namespace/blob/refspec/filepath`, but other Git web-frontends don't work (Gitea, CGit, etc.)

**Comment by dzhou121** [comment]
Shall we leave it for now. It's quite useful sometimes.

**Comment by panekj** [comment]
Closing in favour of error popup

**Pull request closed without merging**
