### PR TITLE
Open editors list can now be collapsed by clicking it

### PR DESCRIPTION
**Pull request by hbina**
Partially solves: https://github.com/lapce/lapce/issues/1398

Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>

- [ ] Added an entry to `CHANGELOG.md` if this change could be valuable to users

### CODE REVIEW

**Comment by dzhou121** [comment]
Thanks for adding this. Would you like to extend it for all ```PanelSectionHeader```?

**Comment by panekj** [comment]
> Sure, but i should probably add some icons to indicate that its expandable. Something like a down_arrow.svg.

https://github.com/lapce/lapce/blob/master/icons/codicons/chevron-down.svg
https://github.com/lapce/lapce/blob/master/icons/codicons/chevron-right.svg

**Comment by dzhou121** [comment]
I would suggest putting the size 0 logic in PanelSection.

**Comment by Gerrit0** [comment]
Would be nice if this could be made persistent - I'd like to never have open editors show up, this would make me collapse the panel every time I open lapce.

**Comment by hbina** [comment]
@dzhou121 I've gotten around to reimplementing it as you requested. It also comes with some cleanup on the array argument because the first element in that tuple was meaningless. Now it serves the purpose of enabling/disabling collapsing of the content. In this case, the warnings/errors panel cannot be collapsed because they are placed side by side.

**Comment by dzhou121** [comment]
Thanks!

**Pull request merged**
