### PR TITLE
Add Fedora build deps and add Matrix Spaces link to README.md

### PR DESCRIPTION
**Pull request by VarLad**

### CODE REVIEW

**Comment by dzhou121** [comment]
Does ```gtk3-devel``` include ```cairo-devel atk-devel cairo-gobject-devel gdk-pixbuf2-devel pango-devel gtk3-devel```?

**Comment by bugadani** [comment]
cc #3

**Comment by VarLad** [comment]
@dzhou121 Just checked, it appears so, yeah. I should probably remove those packages then?

**Comment by dzhou121** [comment]
Yes please. Are those 3 dependencies in Ubuntu enough using Fedora equivalent ones?

**Comment by VarLad** [comment]
@dzhou121 I guess this is the final list

**Comment by dzhou121** [comment]
Thanks!

**Pull request merged**
