### PR TITLE
1. terminal: added support for Alt+ character（some shortcut keys） input

### PR DESCRIPTION
**Pull request by jm-observer**

### CODE REVIEW

**Review by panekj — CHANGES_REQUESTED** [review]
Why does it need to allocate?

**Comment by jm-observer** [comment]
I have a shortcut key alt+/ in the terminal for command completion. However, lapce's terminal doesn't handle alt+/. I believe some people have similar shortcuts, so I added this feature.

**Comment by panekj** [comment]
Ok but it doesn't need to allocate a String for that

**Comment by jm-observer** [comment]
Here, only String can be used.

https://github.com/jm-observer/lapce/commit/86baa4104aae23090a793772c9917e7ee7076f00#:~:text=let%20mut%20rs,(rs)

**Comment by jm-observer** [comment]
Here, only String can be used.
https://github.com/jm-observer/lapce/commit/86baa4104aae23090a793772c9917e7ee7076f00#:~:text=else%20if%20key,(rs)

**Comment by panekj** [comment]
Why close it?

**Comment by jm-observer** [comment]
Maybe there's a better way to do it

**Pull request closed without merging**
