### PR TITLE
add Github Action to do a build on push

### PR DESCRIPTION
**Pull request by SingingBush**
please consider running a CI build on every push to reduce chances of merging changes that break the build

### CODE REVIEW

**Comment by dzhou121** [comment]
I feel like we also need to do a build for Windows and macOS?

**Comment by SingingBush** [comment]
> I feel like we also need to do a build for Windows and macOS?

I totally agree. Do you want me up update this PR or merge this for now and do a follow up?

**Comment by dzhou121** [comment]
Can you please update this PR?

**Comment by dzhou121** [comment]
Oh and no need for --release to make the build faster.

**Comment by SingingBush** [comment]
I've made the required changes so that it now builds on all three platforms. It's also fairly simple to additionally perform the builds with both _stable_ and _nightly_ toolchains. Note that the Ubuntu builds are faster by far so building on all three systems takes about 20 minutes.

I also added a badge to the README so that the build status will be shown on the landing page of the repo once actions are running from your repo.

https://github.com/SingingBush/lapce/actions/runs/2005576765

**Comment by dzhou121** [comment]
Thanks.

**Pull request merged**
