### PR TITLE
fix plugin panel scroll bar

### LINKED ISSUE #779: Plugin panel doesn't scroll
The plugin list is now longer than the plugin panel, but the panel doesn't have a scroll bar nor respond to the scroll wheel or scroll gesture on mac. I have tested on the latest master and scrolling doesn't seem to be supported on plugin panel. 

Test environment: Mac OS 12 on M1

### PR DESCRIPTION
**Pull request by bbrabbitt**
Try to fix #779 

Use `LapceScroll` to wrap the original `Plugin` component.

### CODE REVIEW

**Comment by bbrabbitt** [comment]
I've created a new commit to fix fmt and clippy warnings. Two commits are rebased for better git history.

**Comment by dzhou121** [comment]
You can simply wrap LapceScroll on Plugin itself I think.

**Comment by bbrabbitt** [comment]
> You can simply wrap LapceScroll on Plugin itself I think.

Theoretically yes but I don't know how to do it elegantly. So I imitate what file explorer did, using a wrapper to add LapceScroll to the plugin list.

**Comment by dzhou121** [comment]
Something like this

```
impl Plugin {
    pub fn new() -> Self {
        Self { line_height: 25.0 }
    }

    pub fn new_panel(data: &LapceTabData) -> LapcePanel {
        let split_id = WidgetId::next();
        LapcePanel::new(
            PanelKind::Plugin,
            data.plugin.widget_id,
            split_id,
            vec![(
                split_id,
                PanelHeaderKind::None,
                LapceScroll::new(Self::new()).boxed(),
                None,
            )],
        )
    }
}

```

**Comment by bbrabbitt** [comment]
Thank you for your advice, I'll update the PR accordingly.

**Comment by dzhou121** [comment]
Thanks!

**Pull request merged**
