### PR TITLE
Fix cursor movement in non-vi mode terminal

### LINKED ISSUE #195: Arrow keys don't recall command history in terminal on windows
Pressing any of the arrow keys has no effect, the up arrow doesn't recall the last command and the left and right arrows don't move the cursor.

### PR DESCRIPTION
**Pull request by bugadani**
cc #163
Fixes #195

### CODE REVIEW

**Comment by dzhou121** [comment]
I think we shouldn't catch the keymap and send the keycode in the keydown event. Do you want me to do this?

**Comment by bugadani** [comment]
No, I think I should do this, it should be good practice. I might give up, though :)

But I think it would be weird to handle arrows in the editor, and almost everything except arrows in terminal. Should I add `when = !terminal` (or `mode = <something>`?) to the arrows in the keymaps, so we can handle them like tab/enter/backspace?

**Comment by dzhou121** [comment]
In keymaps file, mode = "inv" would do it.

**Comment by bugadani** [comment]
On that note, do you intend keeping `Terminal` mode? It feels like a bit of a hack to me, since we can have `when` conditions in the keymap. Is there some other reason for the terminal mode?

**Comment by dzhou121** [comment]
That's a good heritage from Neovim. You can go to normal mode and visual mode when you're focusing in Terminal.

**Comment by bugadani** [comment]
> I think we shouldn't catch the keymap and send the keycode in the keydown event.

As far as I can see, alacritty (the app) captures the keys and sends ANSI sequences to the terminal, like [this](https://github.com/alacritty/alacritty/blob/master/alacritty/src/config/bindings.rs#L424) or [with modifiers](https://github.com/alacritty/alacritty/blob/master/alacritty/src/config/bindings.rs#L593).

I'm not sure I can send key codes directly, the best I can do is what `Backspace` does and send ANSI sequences, unless I'm missing something.

**Comment by bugadani** [comment]
So this turned out a bit complex, but hopefully not too complex. I don't know how to "send a character code" with modifiers to the terminal, so I've implemented the most common ansi sequences instead.

**Pull request merged**
