### PR TITLE
feat: add command to reveal item in system file explorer

### PR DESCRIPTION
**Pull request by panekj**
Doesn't actually reveal/select item, since it's currently not possible to do it in druid, but it opens directory fine.

### CODE REVIEW

**Comment by panekj** [comment]
> > Doesn't actually reveal it
> 
> is this a bug in druid, or a limitation?

It's just not implemented since one could argue it's not in scope of GUI library
Definitely not a bug

**Comment by bugadani** [comment]
> Definitely not a bug

Then I'm not exactly sure what's the point of this PR. I would like to avoid nonfunctional UI elements.

**Comment by bugadani** [comment]
> Doesn't actually reveal it

That suggests this PR doesn't do anything. Is this actually working, but the description is misleading?

**Comment by panekj** [comment]
It's working but it doesn't select item in file explorer

**Comment by bugadani** [comment]
Oh that's fine, apologies then.

**Comment by panekj** [comment]
My point is that this should be done via native platform API (e.g. Windows https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shopenfolderandselectitems) but it's not implemented in druid and I think it would be best if it was there together with `OpenURI` logic. Someday I might implement it there.
For now it's implemented in a "hack way" by passing path to system to open it via default application.

**Review by bugadani — APPROVED** [review]

**Pull request merged**
