### PR TITLE
Fix click-to-toggle panels

### LINKED ISSUE #218: UX: only the source control side panel can be closed, the others can't.

### PR DESCRIPTION
**Pull request by bugadani**
Closes #218

### CODE REVIEW

**Comment by bugadani** [comment]
The special-casing causes a different behaviour than VSCode and makes the implementation slightly more complex. I personally wouldn't keep it, but it was how the SourceControl panel worked before, so I left it in.

**Comment by dzhou121** [comment]
We might be a toggle_panel_visual and toggle_panel_focus

toggle_panel_visual is for mouse clicks, and toggle_panel_focus is for key presses.

**Comment by dzhou121** [comment]
We might be a toggle_panel_visual and toggle_panel_focus

toggle_panel_visual is for mouse clicks, and toggle_panel_focus is for key presses.

**Comment by bugadani** [comment]
What would be the difference in behavior?

**Comment by dzhou121** [comment]
E.g., when the focus is in the editor and the terminal is open, toggle_panel_focus will jump the focus to the terminal, while toggle_panel_visual will close the terminal. 

If the focus is on the terminal, both toggle_panel_focus and toggle_panel_visual will close the terminal panel.

**Comment by bugadani** [comment]
I hope I understood you correctly. Clicks now work as focus commands, but they also fall back to visibility-based toggling for the panels that don't focus.

The other option I had was, to not define `Focus` variants for those panels, but I think this is a bit more simple to extend in the future.

**Comment by bugadani** [comment]
Note that CI isn't green on this one (yet), but github has issues and a run has not been scheduled.

**Pull request merged**
