### PR TITLE
add .cargo.toml

### PR DESCRIPTION
**Pull request by kotlin2018**
- [ ] Added an entry to `CHANGELOG.md` if this change could be valuable to users

### CODE REVIEW

**Comment by panekj** [comment]
what's the purpose of this?

**Comment by kotlin2018** [comment]
> what's the purpose of this?

Accelerate download dependency

**Comment by panekj** [comment]
> > what's the purpose of this?
> 
> Accelerate download dependency

you can put that config in `CARGO_HOME/config.toml`

**Comment by Titaniumtown** [comment]
Why isn't this a change you just do on your local machine?

**Comment by kotlin2018** [comment]
> > > what's the purpose of this?
> > 
> > 
> > Accelerate download dependency
> 
> you can put that config in `CARGO_HOME/config.toml`

OK, thank you for your reply

**Comment by kotlin2018** [comment]
> Why isn't this a change you just do on your local machine?

Ok

**Pull request closed without merging**
