### PR TITLE
Standardizes command messages

### PR DESCRIPTION
**Pull request by thiagola92**
Added `#[strum(message = "MESSAGE")]` to all shortcuts commands and changed all to start with capital letter following by lower case letters

- [ ] Added an entry to `CHANGELOG.md` if this change could be valuable to users

### CODE REVIEW

**Comment by panekj** [comment]
We use capital letters everywhere, so I would like it to stay that way

**Comment by thiagola92** [comment]
> We use capital letters everywhere, so I would like it to stay that way

Sorry, I found two styles in the file so I made a guess

**Comment by panekj** [comment]
There are conflicts to resolve in `lapce-core/src/command.rs`

**Comment by MinusGix** [comment]
That is due to the move of the editor into floem, with the file now located at: https://github.com/lapce/floem/blob/main/editor-core/src/command.rs

**Pull request closed without merging**
