### PR TITLE
feat: fork by default when started from terminal

### PR DESCRIPTION
**Pull request by Arjun31415**
- [x] Added an entry to `CHANGELOG.md` if this change could be valuable to users

### CODE REVIEW

**Comment by panekj** [comment]
Fixes #1169

**Comment by dzhou121** [comment]
Does this affect macOS/windows 'APP' startup?

**Comment by panekj** [comment]
It shouldn't break anything

**Comment by panekj** [comment]
> Can you maybe make it Linux only for now?

Fix in https://github.com/lapce/lapce/pull/1658

**Pull request merged**
