### PR TITLE
Code action change

### PR DESCRIPTION
**Pull request by dzhou121**
- [ ] Added an entry to `CHANGELOG.md` if this change could be valuable to users

### CODE REVIEW

**Comment by dzhou121** [comment]
@TudbuT Would you mind testing this which improves the code actions cache.

**Comment by TudbuT** [comment]
The first of these commits is redundant, as the issue is not there being no code action, its there being wrong code actions. I think we only need to clear the cache on update to be able to enable it again.

**Comment by dzhou121** [comment]
> Oh, that makes sense. We'd also have to clear whenever we get a new EditorDiagnostic, as some LSPs rely on those and wont provide quick fixes otherwise.

Done in latest commit

**Comment by TudbuT** [comment]
Looks good to me, tho as said in the review, that check is a little bit cluttered in my opinion :P

**Pull request merged**
