### PR TITLE
fix settings page navigation issue

### LINKED ISSUE #2759: [Bug Report] Settings page navigation exceptions
## Lapce Version

0.3.0 

## System information

Windows 11

## Describe the bug
Sometimes, when we click on the navigation on the left side of the settings page, the settings do not jump to the specified position correctly. Especially the ones that are lower down. This is episodic, and the pattern of its appearance is not yet known.
## Additional information

For example, click the tab of "Terminal Settings", it wont jump to the settings about terminal. 
image

### PR DESCRIPTION
**Pull request by Long0x0**
Fixes #2759.

- [ ] Added an entry to `CHANGELOG.md` if this change could be valuable to users

### CODE REVIEW

**Comment by panekj** [comment]
This still doesn't jump correctly to clicked elements

**Comment by Long0x0** [comment]
hmm, have checked on windows and ubuntu, seems to be no problem.
which platform do you use?

**Comment by panekj** [comment]
Windows

**Comment by panekj** [comment]
Probably cargo being dumb again, it works after clean build

**Pull request merged**
