### PR TITLE
fix panel resizing bug

### LINKED ISSUE #2832: Resizing panel mouse position bug
## Lapce Version

HEAD

## System information

Linux. Gnome (Wayland) + PaperWM
No alternative display scaling

## Describe the bug
When resizing the panel with the mouse, the coloration when the mouse hovers over the left panel works fine. However upon clicking, it jumps and is noticeably to the left as you drag.

## Additional information
image
(taken while dragging)

### PR DESCRIPTION
**Pull request by Long0x0**
Fixes #2832.

- [ ] Added an entry to `CHANGELOG.md` if this change could be valuable to users

animation

### CODE REVIEW

**Comment by panekj** [comment]
Is there a reason why we resize other side panel when touching side panel size?

**Comment by panekj** [comment]
btw. ignore clippy for now, since new rust just releases, we get new failing lints unfortunately

**Comment by panekj** [comment]
Could you rebase or merge latest master?

**Comment by Long0x0** [comment]
> Is there a reason why we resize other side panel when touching side panel size? @MinusGix @dzhou121

Oh, this reminds me of the real bug.

**Comment by Long0x0** [comment]
Now it works as expected.

**Comment by MinusGix** [comment]
Nice, thanks for fixing both.

**Pull request merged**
