### PR TITLE
fix: update toml_edit and use toml crate for easy parsing

### PR DESCRIPTION
**Pull request by panekj**
- [ ] Added an entry to `CHANGELOG.md` if this change could be valuable to users

### CODE REVIEW

**Comment by dzhou121** [comment]
What’s the benefit of this?

**Comment by panekj** [comment]
`toml_edit` removes `easy` feature in newer versions

**Comment by panekj** [comment]
https://github.com/toml-rs/toml/blob/25fafe6766e8f7bf5353ea8a1afbf889ae38e9b2/crates/toml_edit/CHANGELOG.md?plain=1#L105

**Comment by panekj** [comment]
It's also to remove duplicate crate versions but since everything is connected and depends on each other it's quite hard to do properly at once

**Comment by panekj** [comment]
> additional toml crate?

We already have it in lockfile so it's not really additional

https://github.com/lapce/lapce/blob/f36c9612edd9db1504f30a5650583ba0d0318e51/Cargo.lock#L4836-L4843

**Comment by dzhou121** [comment]
Got it. Thanks!

**Pull request merged**
