### PR TITLE
fix:reimplementing EnableModal and DisableModal command

### PR DESCRIPTION
**Pull request by tk103331**
- [ ] Added an entry to `CHANGELOG.md` if this change could be valuable to users

Reimplementing EnableModal and DisableModal command
https://github.com/lapce/lapce/issues/2417

### CODE REVIEW

**Comment by MinusGix** [comment]
This has the issue that it won't change the current cursor mode, I believe.   
Our previous impl uses some logic when modal-mode changes to then update the cursor's mode in some reasonable way.  
https://github.com/lapce/lapce/blob/master/lapce-ui/src/editor/view.rs#L972
Which uses  
https://github.com/lapce/lapce/blob/master/lapce-core/src/editor.rs#L1411 for `InsertMode`
https://github.com/lapce/lapce/blob/master/lapce-core/src/editor.rs#L1411 for `NormalMode`  
  
`Document` has its `do_edit` function which would work for this. I presume it would need to be applied to all open editors (all open window tabs and their editors?)

**Comment by tk103331** [comment]
I am referring to the original implementation，just call `LapceConfig::update_file`.

https://github.com/lapce/lapce/blob/3d921f662da9ea885e3d50b29ab39ce2ab59a59b/lapce-data/src/data.rs#L1461-L1478

**Comment by MinusGix** [comment]
The original had implicit side-effects of updating the cursor when the modal mode changed which we don't have currently.  
  
You don't have to implement those side-effects in your PR, but it does mean that the cursor will behave weirdly when changing modal mode. If you want, I can just have a separate issue for updating the cursor.

**Comment by tk103331** [comment]
I understand what you mean, it should be better to open another issue.

**Pull request merged**
