### PR TITLE
Collapsible problem groups

### LINKED ISSUE #609: Request: Collapse file sections in problems view
It would be nice if I was able to collapse warnings / errors from specific files in the problems view.

### PR DESCRIPTION
**Pull request by bugadani**
Supersedes #611 
Resolves #609

### CODE REVIEW

**Comment by bugadani** [comment]
So far I haven't done much. I've rebased and fixed a crash, but I have not really dug into the actual feature. What's obvious is that we should add some sort of indicator next to the collapsed file's name.

**Comment by bugadani** [comment]
Sorry, there's still something I want to do

**Comment by bugadani** [comment]
As I can't make it crash anymore, @dzhou121 this is ready for you.

**Review by panekj — APPROVED** [review]
Looks ok to me

**Pull request merged**
