### PR TITLE
Refactor towards testability, step 5: Remove some unnecessary clones

### PR DESCRIPTION
**Pull request by bugadani**
The testability related change in this is passing proxy by reference, instead of a clone of its `Arc`. The rest is just general cleanup.

### CODE REVIEW

**Comment by bugadani** [comment]
Rebased

**Comment by bugadani** [comment]
@dzhou121 is there any point for me to rebase this, or would I just be wasting my time?

**Comment by dzhou121** [comment]
Sorry for breaking your PR again. Maybe let’s leave it for now.

**Comment by bugadani** [comment]
I have decided to rebase because the conflicts weren't serious and I think the changes are worth keeping this up to date.

**Comment by bugadani** [comment]
Closed in favour of #350

**Pull request closed without merging**
