### PR TITLE
Add Java syntax

### PR DESCRIPTION
**Pull request by lucianoseibel**
Added java syntax by tree-sitter-java github project

### CODE REVIEW

**Comment by dzhou121** [comment]
The ```package.json``` doesn't seem right. It doesn't compile for me.

**Comment by Tiggilyboo** [comment]
I have created https://github.com/lapce/lapce/issues/272 to track these

**Comment by bugadani** [comment]
Please clean up the `Cargo.lock` changes, so the diff is of a more manageable size. Thank you!

**Comment by bugadani** [comment]
Closing in favour of #429 due to inactivity.

**Pull request closed without merging**
