### PR TITLE
Adding support for the dart language (help needed)

### PR DESCRIPTION
**Pull request by franklinblanco**
Hello, great codebase you got, it's become my favorite editor in about 2 days of use. Even though there are some bugs it's FOSS & speed > anything else for me. 

I'm here today because I do flutter + rust development and I found a tree_sitter_dart crate. So I followed the EXTREMELY WELL Documented instructions on how to add a language in lapce-core/Language.rs

I did everything. But I'm getting this one problem I can't solve: 
Screen Shot 2022-09-11 at 11 46 56 AM

Followed the web on this one and found this: 
[Answer to the error](https://stackoverflow.com/questions/27895946/expected-fn-item-found-a-different-fn-item-when-working-with-function-pointer)

But couldn't seem to work it out as the answer had primitive function return types and in this case it's a struct return type. tree_sitter::Language.

So, I've rattled a bit and tried to find what I can do, but I'm a bit lost. I see you guys are very active and would appreciate at least some guidance here! Thanks!

Mentioned in #1125

### CODE REVIEW

**Comment by panekj** [comment]
Error means that the library is using incompatible version of `tree-sitter` dependency

**Comment by franklinblanco** [comment]
> Error means that the library is using incompatible version of `tree-sitter` dependency

Holy! Thank you that was so quick, I'm going to fork it and attempt to update it!!

**Comment by franklinblanco** [comment]
Now it's this, guess I'm gonna do some more research before moving on with this
Screen Shot 2022-09-11 at 11 58 22 AM

**Comment by ghishadow** [comment]
try using https://github.com/syntacti/tree-sitter-dart if it works

**Comment by franklinblanco** [comment]
@ghishadow That seemed to compile correctly. I'm going to build it locally and test a dart project. Thank you very much for your help!!!

**Comment by franklinblanco** [comment]
Done! @ghishadow Tested, works just fine, thank you millions for the help, thinking of supporting the project with a small donation, is there a preferred route?

**Comment by panekj** [comment]
> thinking of supporting the project with a small donation, is there a preferred route?

nope

**Comment by franklinblanco** [comment]
@panekj Sorry about that! Forgot to rename a test

**Pull request merged**
