### PR TITLE
Render whitespace

### PR DESCRIPTION
**Pull request by Nykseli**
Adding simple logic for whitespace rendering. Rendering logic is similar to VSCode.
Notably this doesn't take selected text into account. So this doesn't implement the `selection` whitespace rendering option.

Feature request: https://github.com/lapce/lapce/issues/249

### CODE REVIEW

**Review by bugadani — COMMENTED** [review]
Thank you, this looks promising!

I have one nit to pick: would it be possible to replace the "push-in-loop" style appending with `string.extend(iter)` instead?

I'm also cc'ing #302 - if we'll ever have dropdowns, we could think about turning the setting into an enum and avoid string comparisons.

**Comment by Jerrody** [comment]
> we could think about turning the setting into an enum and avoid string comparisons.

What about [hashing](https://doc.rust-lang.org/std/hash/trait.Hash.html)?

**Comment by Nykseli** [comment]
> I have one nit to pick: would it be possible to replace the "push-in-loop" style appending with string.extend(iter) instead?

Line 2027:
```rust
for _ in whitespace_buffer.iter() {
    rendered_whitespaces.push(' ');
}
```
And line 2043:
```rust
whitespace_buffer
    .iter()
    .for_each(|c| rendered_whitespaces.push(*c));
```

Can be easily turned into
```rust
rendered_whitespaces.extend(whitespace_buffer.iter());
```

And I agree that it's a lot cleaner that way. Would that be enough? I think removing other "push-in-loops" require rewriting the whole logic.

> we could think about turning the setting into an enum and avoid string comparisons.

I agree with using enums. They are easy to implement, easy to understand and the comparisons are fast. And they even work well if/when the UI starts supporting translations.

**Comment by bugadani** [comment]
> I think removing other "push-in-loops" require rewriting the whole logic.

Not really, I was only referring to those 3-liner snippets you quoted (I saw 3 of those I think). So yup, that's probably enough here :)

**Comment by Jerrody** [comment]
> we could think about turning the setting into an enum and avoid string comparisons.

About this variant of using enum instead of strings.
Exists great crate for this purposes: [strum](https://crates.io/crates/strum).

I want to rewrite little bit a `LapceUICommand` enum to be easy to maintain a command's naming via enum's variant. Without look in many places of code an changing this name.

**Comment by Nykseli** [comment]
Added a commit that uses extend where it makes sense.

> I saw 3 of those I think

There was 3 but one of those was pushing `n` amount of empty spaces (I actually copied that snipped in my previous comment) and I don't think there is cleaner/faster way to add `n` amount of spaces at the end of a string. I might be wrong though.

**Pull request merged**
