### PR TITLE
Avoid receiving the terminal disconnection event before the terminal …

### PR DESCRIPTION
**Pull request by jm-observer**
Avoid receiving the terminal disconnection event before the terminal has finished reading, which leads to incorrect display.

### CODE REVIEW

**Comment by dzhou121** [comment]
maybe just drain the pty like this https://github.com/alacritty/alacritty/blob/master/alacritty_terminal/src/event_loop.rs#L268

**Comment by jm-observer** [comment]
I've tried, but I still can't read all the data in this loop

**Comment by dzhou121** [comment]
How can I replicate this issue?

**Comment by jm-observer** [comment]
I'm doing a cargo check on a small project, and it either stops, doesn't show all, or there's no problem

**Comment by dzhou121** [comment]
> I'm doing a cargo check on a small project, and it either stops, doesn't show all, or there's no problem

Is this "Run and Debug"?

**Comment by jm-observer** [comment]
here：image

**Comment by jm-observer** [comment]
?

**Comment by jm-observer** [comment]
I encountered it in a windows environment

**Pull request merged**
