### PR TITLE
Development environment for lapce using devcontainer

### PR DESCRIPTION
**Pull request by akhildevelops**
I felt it would be great to have a devcontainer easing the pain for lot many contributors to setup environment.

Few of the them even mentioned for the need of it.https://github.com/lapce/lapce/issues/2235

Here's the devcontainer.json file that can be used to setup development environment in docker and build lapce.

Running the binary creates a seperate gui window that uses host's X11 server.

Reference: http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/

image

### CODE REVIEW

**Comment by panekj** [comment]
I would like to not depend on specific host configuration and hacks

**Comment by akhildevelops** [comment]
What do you mean by hacks ?

**Comment by panekj** [comment]
It requires X11?

**Comment by akhildevelops** [comment]
Yup

**Comment by panekj** [comment]
That's a hack, that's a very specific host dependency

**Comment by akhildevelops** [comment]
I believe it also works on wayland with few changes, lemme check and come back.

**Comment by akhildevelops** [comment]
For further reference: https://github.com/mviereck/x11docker/wiki/How-to-provide-Wayland-socket-to-docker-container

**Comment by akhildevelops** [comment]
Closing this as it cannot be built for majority of display servers

**Pull request closed without merging**
