### PR TITLE
Add Nix flake

### PR DESCRIPTION
**Pull request by enderger**
- [ ] Added an entry to `CHANGELOG.md` if this change could be valuable to users

### CODE REVIEW

**Comment by panekj** [comment]
Please see https://github.com/lapce/lapce/issues/1049

**Comment by panekj** [comment]
Since nix manifests can be defined in nixpkgs, it's preferable that it's maintained in Nix repo. Closing for now.

**Comment by poelzi** [comment]
😢 
a nix flake in the dev repo is not the same thing as a nixpkgs. nixpkgs is meant as a stable product, a flake allows you to build and test the dev version.
A proper flake and you can test a pr with one command or add a specific branch/pr with not much fuzz to any system.

**Comment by LiGoldragon** [comment]
To have a project without a nix flake is to live in the stone age.

**Pull request closed without merging**
