### PR TITLE
Set the Palette to default to the Help Palette.

### PR DESCRIPTION
**Pull request by jm-observer**
This makes it more convenient for the user.

help

### CODE REVIEW

**Comment by dzhou121** [comment]
I probably would keep it as is because:

1) There's a search icon on the palette input bar before it was clicked so it kind of suggests it should be a file search

2) Maybe it would be better if it's a setting?

**Comment by jm-observer** [comment]
reasons i commit this pr:
1. I often forget the symbols for various functions.I think many people have the same concern.
2. I noticed that VSCode now also sets the Help Palette as the default, which wasn't the case before.

https://github.com/user-attachments/assets/a6f8898e-9b54-4239-aaba-f7c3300f96ea

**Comment by dzhou121** [comment]
Got you. 

It still have one issue, that when you do ctrl+p, it still shows the help.

**Comment by jm-observer** [comment]
If the default is the Help item, we can refer to VSCode: when accessed via a shortcut key, it should show file search instead of the Help item.

**Comment by jm-observer** [comment]
the effect as follow:

**Pull request merged**
