### PR TITLE
Fix build warnings, minor line ending issues

### PR DESCRIPTION
**Pull request by U007D**

### CODE REVIEW

**Comment by U007D** [comment]
For a very long time, I have wanted to write something between an IDE and an editor (most recently, in Rust) to address the concerns I have with existing tools.  `lapce` proves that I am not alone with this desire.

With an eye to potentially becoming a contributor, I thought I could clean up the build warnings in the process of familiarizing myself with the codebase and provide something of benefit to the community.

Xie xie to @dzhou121 for creating `lapce` this and being willing to share it with the world.

**Comment by bugadani** [comment]
I'd be happy to rebase my PRs on top of this.

**Comment by U007D** [comment]
I see now I should probably have made PR's directly from the `fix-warnings` and `organize-deps` branches, since changes to my fork of `master` are accumulating in this one PR.

Rest assured, I am done for now; over the next couple of weeks, my next step is to look at some unit tests, since `lapce` appears to be a little light ;) in that department.

:)

**Comment by dzhou121** [comment]
Thanks so much for your PR. Adding unit tests sounds great :)

**Comment by bugadani** [comment]
So, a lot has changed in these past few months. I'm closing this PR as it would be much more work to get it rebased than it's worth, and I'm not sure if we need this any more. Thanks for your work, though!

**Pull request closed without merging**
