### PR TITLE
Popout menus now appear beneath their buttons, instead of at (0, 0)

### PR DESCRIPTION
**Pull request by Wcubed**
Like so:
afbeelding

### CODE REVIEW

**Comment by panekj** [comment]
Isn't this duplicate of #2569

**Comment by Wcubed** [comment]
Wow, it is. Just saw it. That one was opened literally 30 minutes ago XD

**Comment by zarathir** [comment]
I can close my PR, since I'm unable to test the changes

**Comment by burrbull** [comment]
I don't see any popup menu at all pressing at that button. Button blinks but no more reaction.
Ubuntu 23.04, nightly lapce

0.2.8 works fine

**Comment by Wcubed** [comment]
> I don't see any popup menu at all pressing at that button. Button blinks but no more reaction. Ubuntu 23.04, nightly lapce
> 
> 0.2.8 works fine

Are you running Wayland? Currently nightly does sadly not support linux (see #2417). It is being worked on in the `glazier` dependency if I recall correctly.

**Comment by burrbull** [comment]
> Are you running Wayland? Currently nightly does sadly not support linux (see #2417). It is being worked on in the `glazier` dependency if I recall correctly.

No. xorg. kwin

**Pull request merged**
