### PR TITLE
tree-sitter: Add the .slint UI language

### PR DESCRIPTION
**Pull request by flukejones**
- [x] Added an entry to `CHANGELOG.md` if this change could be valuable to users

This is paired with https://github.com/lapce/tree-sitter-grammars/pull/28

I don't know if this is the correct method to go about this. There does not appear o be much documentation about adding languages.

Slint is a UI made with rust https://slint.dev/

### CODE REVIEW

**Comment by panekj** [comment]
We don't accept more grammars built-in to lapce

**Comment by panekj** [comment]
The grammar is not open source so it can't be added

**Comment by aurindam** [comment]
@panekj Its licensed under GPLv3.

**Comment by panekj** [comment]
@aurindam it is absolutely not, there is a [directory](https://github.com/slint-ui/tree-sitter-slint/tree/master/LICENSES) with 3 different licences without any guidance what is supposed to be used (probably same how slint is licenced but I'm not going to be guessing)

`Cargo.toml`, `pyproject.toml` and etc. specify `MIT`, which means that no one bothered to actually licence that repository properly

**Comment by aurindam** [comment]
@panekj Would a README in that folder clarifying that its triple licensed (like Slint) be sufficient?

**Comment by panekj** [comment]
@hunger Thank you, it definitely works for me and assures the status of grammar "legality" :)

**Comment by panekj** [comment]
Nope (unless you're interested in preparing queries for Lapce), I'm in progress of restructuring (and adding much more) grammars here: https://github.com/lapce/tree-sitter-grammars/tree/be-less-stupid
Languages/queries are updated here: https://github.com/lapce/lapce/pull/3279 (partially, will be cherry-picked to master once ready) but we're planning on moving queries to the repo with grammars

Overall its just time consuming (and tedious) to prepare logic for updating and distributing grammars.

**Comment by flukejones** [comment]
@panekj will you be managing this from now, or shall I update and reopen the PR?

**Comment by panekj** [comment]
> @panekj will you be managing this from now, or shall I update and reopen the PR?

If you remove the tree-sitter grammar (just add the Syntax definition and slint LSP id in proxy buffer) I'll merge it

**Comment by flukejones** [comment]
@panekj should be good to reopen and merge now I think

**Pull request closed without merging**
