### PR TITLE
app: quit on custom key shortcut.

### PR DESCRIPTION
**Pull request by azizk**
My first pull request. :grin:

### CODE REVIEW

**Comment by MinusGix** [comment]
This fixes #681.  
Though, like mentioned there: I'm mildly against having the default keybinding for quitting be Ctrl+Q due to its location typically (on qwerty) being near commonly used keys like Ctrl+W (close tab) and Ctrl+Tab (change tab). It is good to have a command for that, though.

**Comment by panekj** [comment]
> Though, like mentioned there: I'm mildly against having the default keybinding for quitting be Ctrl+Q due to its location typically (on qwerty) being near commonly used keys like Ctrl+W (close tab) and Ctrl+Tab (change tab). It is good to have a command for that, though.

This, but also I'm strongly against that keybind because it's specific to one platform only (macOS) while other platforms have different defaults for such action (e.g. Windows - `LAlt` + `F4`)

**Comment by jath03** [comment]
> it's specific to one platform only (macOS

Personally I've tried to quit the editor with Ctrl+Q on linux and was disappointed that it didn't work, but I understand if you all don't want it enabled by default.

Do we want to come up with an alternative binding or just leave it unbound by default?

**Comment by panekj** [comment]
> Do we want to come up with an alternative binding or just leave it unbound by default?

It should be unbound by default but available for user to bind. There should be provided another keybind for platform specific implementation (macOS injects CMD+Q so no binding(?), on Windows `LAlt` + `F4` needs to be manually binded by lapce, Linux (GNOME/KDE/etc.)???)

**Comment by azizk** [comment]
Well, I see where you're coming from, but I don't think it's such an issue for several reasons:

1. I've probably never hit Ctrl+Q accidentally in all the years I've been programming with Sublime Text. And if I did it was no biggie. The editor restores unsaved changes/files.
2. Many other applications have the Ctrl+Q and Ctrl+W bindings, for example: Firefox (Linux). Notably Chromium doesn't have a default binding for quitting.
3. Binding it to something else would go against the grain. I think I remember from my Windows days that Ctrl+Q was quite common.

So yeah, I can see the usability aspect but on the other hand it's pretty much standard and it's never been a problem. It should especially not be a problem once Lapce saves and restores files that haven't been saved yet.

**Comment by azizk** [comment]
> > Though, like mentioned there: I'm mildly against having the default keybinding for quitting be Ctrl+Q due to its location typically (on qwerty) being near commonly used keys like Ctrl+W (close tab) and Ctrl+Tab (change tab). It is good to have a command for that, though.
> 
> This, but also I'm strongly against that keybind because it's specific to one platform only (macOS, although CMD + Q is done by system already) while other platforms have different defaults for such action (e.g. Windows - `LAlt` + `F4`)

It's not just for macOS. I'm on Xfce Manjaro and there are a few apps that have that binding.

`LAlt+F4` is also a common shortcut on Linux. It closes or should close the current window, but not the whole application. I think it behaves the same on Windows.

That's what I'm missing. Closing the app with a shortcut and having all windows + unsaved files restored on restart.

**Comment by panekj** [comment]
> So yeah, I can see the usability aspect but on the other hand it's pretty much standard and it's never been a problem. It should especially not be a problem once Lapce saves and restores files that haven't been saved yet.

Just because it's mitigated doesn't mean we should introduce a behaviour that would reduce user UX.

> 1. I've probably never hit Ctrl+Q accidentally in all the years I've been programming with Sublime Text. And if I did it was no biggie. The editor restores unsaved changes/files.

It's only your experience but we should always think about all users.

> 2. Many other applications have the Ctrl+Q and Ctrl+W bindings, for example: Firefox (Linux). Notably Chromium doesn't have a default binding for quitting.

Firefox (Windows) = `Ctrl` + `Shift` + `Q`
Chromium-based browsers = no binding
VSCode = No binding, `LeftAlt` + `F4` closes VSC window
Intellij = No binding

**Comment by jath03** [comment]
All on Linux
Firefox = Ctrl+Q
Discord = Ctrl+Q
vscodium = Ctrl+Q
atom = Ctrl+Q

These are all browser/electron based though, so maybe Ctrl-Q just originated from there?  

I think we should do like a poll on discord or something to see what people want for the default, because that's ultimately what matters most: what the users want, right?

**Comment by panekj** [comment]
> I think we should do like a poll on discord

I think not, ~25 users should not decide fate of rest of the userbase

> or something to see what people want for the default, because that's ultimately what matters most: what the users want, right?

No, because not every user uses all platforms and we should not introduce a new behaviour onto a platform.

> That's what I'm missing. Closing the app with a shortcut and having all windows + unsaved files restored on restart.

I'll give you an offer, remove the default keybind and the PR can get merged (almost) instantly.
We can discuss default keybind later under separate issue/discord.

**Comment by azizk** [comment]
Ok! I just left it in commented out if that's alright. I also added `"Quit Editor"` as the command's message, renamed `"quit_app"` and `"QuitApp"` to `"quit"`/`"Quit"` and moved the `LapceWorkbenchCommand::Quit` case to the bottom of the match statement. :+1:

**Comment by bugadani** [comment]
I think without the defaults this PR should not be controversial and should be good to go.

(Side note: Interesting that I can't link #681 to this PR in the "Development" section to the right.)

**Pull request merged**
