### PR TITLE
Refactor command.rs

### PR DESCRIPTION
**Pull request by amab8901**
- [ ] Added an entry to `CHANGELOG.md` if this change could be valuable to users

### CODE REVIEW

**Comment by panekj** [comment]
This seems unnecessary

**Comment by amab8901** [comment]
> This seems unnecessary

the code is currently messy and hard to find around. Refactoring makes it easier for newcomers like myself to find a specific item in a long list, given that I haven't memorized the whole list

**Comment by panekj** [comment]
> > This seems unnecessary
> 
> the code is currently messy and hard to find around. Refactoring makes it easier for newcomers like myself to find a specific item in a long list, given that I haven't memorized the whole list

this just sorts everything and adds noise in git log, I don't see how that hinders ability to use search or go to symbol

**Comment by amab8901** [comment]
Imagine having a dictionary where the words are just put there in random order. It would be kinda hard to get an overview of what's available when learning the codebase

**Comment by panekj** [comment]
but this is not a dictionary, it's a codebase, which you can easily ctrl+f or go by reference/symbol

**Comment by amab8901** [comment]
> but this is not a dictionary, it's a codebase, which you can easily ctrl+f or go by reference/symbol

if I know the name of the item, then I can use ctrl+F. But what if I'm exploring the list to see what's available?

**Comment by panekj** [comment]
Then you can read? Still it doesn't require everything to be sorted

**Comment by amab8901** [comment]
> Then you can read? Still it doesn't require everything to be sorted

yeah I can read, but I think that having it sorted makes it easier for me to navigate it. Let's suppose I'm looking for an item that begins with `Update...`. If it's sorted, then I have them all in one place instead of having to jump around to different parts of the code

**Comment by amab8901** [comment]
this refactoring also sorts items by how many arguments they take in. Let's suppose I'm looking for an item that takes 3 arguments as input. I have them all in one place so that there are fewer items I need to go through

**Comment by amab8901** [comment]
> this just sorts everything and adds noise in git log,

the noise in git log can be solved by git rebase, where you merge this commit into one of its neighbors in the git log

**Pull request closed without merging**
