### PR TITLE
Fix/terminal-background

### PR DESCRIPTION
**Pull request by evnct**
- [ ] Added an entry to `CHANGELOG.md` if this change could be valuable to users
Fixes -> #2772

### CODE REVIEW

**Comment by dzhou121** [comment]
panel items don't have backgrounds set including terminal so that when they are at the bottom, they will be the same as editor background. So if you drag the terminal panel to the right or left, it will have the panel background.

**Comment by ElmeriVincent** [comment]
You mean like this (dragging it to the right)? 

Screenshot from 2023-11-14 23-36-37

**Comment by dzhou121** [comment]
Yes.

terminal.background probably shouldn't be there to confuse people.

**Comment by ElmeriVincent** [comment]
Checking if I understood right. What is in the image now at the bottom right side should have the editor background and what is at the top right should have panel background?

**Pull request closed without merging**
