### PR TITLE
lapce-proxy: fix flatpak host detection

### PR DESCRIPTION
**Pull request by bugadani**
Supersedes #1157 and #1151

This PR
 - cleans up a block comment (a bit of style consistency)
 - only executes the flatpak command if the info file exists
 - does not crash on error

### CODE REVIEW

**Review by Newbytee — APPROVED** [review]
Looks great! I like that it doesn't needlessly shell out when `/.flatpak-info` doesn't exist.

**Review by panekj — APPROVED** [review]

**Comment by bugadani** [comment]
Let's hope this actually works, as I use Windows and this code is grayed out for me :P

**Comment by Newbytee** [comment]
I can test it, one moment.

**Comment by panekj** [comment]
Logic is sound and clippy didn't complain on Linux so I think it's ok

**Comment by VolatileMark** [comment]
Works on my system (Fedora 36)

**Comment by Newbytee** [comment]
> Works on my system (Fedora 36)

Same here when running on the host, but I'm currently waiting for the Flatpak build to finish so I can test that too.

**Comment by Newbytee** [comment]
Tested both Flatpak-contained with and without the Flatpak talk name, and also host both with and without `flatpak-spawn` installed. All four cases worked as expected! :tada:

**Pull request merged**
