### PR TITLE
（Draft）feat: support increase diff extend size

### PR DESCRIPTION
**Pull request by tk103331**
- [x] Added an entry to `CHANGELOG.md` if this change could be valuable to users

feature: support increase diff extend size

image

click the area will increase the diff extend size, now wil plus 5 lines.

image

### CODE REVIEW

**Comment by tk103331** [comment]
In the future, a code comparison toolbar can be made, like other IDEs

JetBrains:
image

**Comment by dzhou121** [comment]
This is. Very good feature! Would you mind adding it to CHANGLOG.md?

**Comment by tk103331** [comment]
I found some bugs, I will make a new PR when I fix them

**Comment by panekj** [comment]
You could leave it open as draft :)

**Comment by tk103331** [comment]
new pr: https://github.com/lapce/lapce/pull/1979

**Pull request closed without merging**
