### PR TITLE
1. editor: Right-click add command "Show Call Hierarchy"

### PR DESCRIPTION
**Pull request by jm-observer**
1. editor: Right-click add command "Show Call Hierarchy".Currently, only the interaction with the lsp is complete, and the result is not rendered

2. fixed warnings in clippy report

### CODE REVIEW

**Comment by dzhou121** [comment]
Maybe we don't put it in the context menu for now?

**Comment by jm-observer** [comment]
why not?

**Comment by jm-observer** [comment]
No, it's getting the name of the mouse position function

**Comment by dzhou121** [comment]
I mean from a user's perspective, it doesn't "work" when you click "Show Call Hierarchy" in the context menu. So let's hide it for the moment and expose it when it's fully implemented.

**Pull request merged**
