### PR TITLE
feat: add Svelte & LaTeX

### PR DESCRIPTION
**Pull request by panekj**
Signed-off-by: Jakub Panek <me@panekj.dev>

### CODE REVIEW

**Comment by franklinblanco** [comment]
Dang, was just done with Adding svelte, about to create a PR and saw this, good catch. Nice to see such a good OS community

**Comment by panekj** [comment]
> Dang, was just done with Adding svelte, about to create a PR and saw this, good catch. Nice to see such a good OS community

It's better to just mention them in #272 so we can add bunch of them at the same time as each PR causes conflict

**Comment by zero-edge** [comment]
Please forgive me if this is obvious, but how do I use the newly merged Svelte language support?

**Comment by panekj** [comment]
> Please forgive me if this is obvious, but how do I use the newly merged Svelte language support?

You can't because it's not included in 0.2.0

**Pull request merged**
