### PR TITLE
(properly) fix opening bash files crashing lapce

### PR DESCRIPTION
**Pull request by TudbuT**
- [x] Added an entry to `CHANGELOG.md` if this change could be valuable to users

Better version of #1764

Closes: #1762

### CODE REVIEW

**Review by panekj — CHANGES_REQUESTED** [review]
Blocking merging because I'd like to test myself what's wrong with query and where the problem appeared :)

**Comment by TudbuT** [comment]
Alright!

**Comment by TudbuT** [comment]
I can tell you tho: the (expansion_flags) item broke it.

**Comment by TudbuT** [comment]
I also fixed a slight formatting mistake in the bash file along the way, but that didn't change any behavior.

**Comment by TudbuT** [comment]
any news?

**Comment by TudbuT** [comment]
replaced by #1771

**Pull request closed without merging**
