### PR TITLE
Added more parity with the website

### LINKED ISSUE #401: Readme readability additions
Added some more parity with the website and some changes to make it easier to read.
Pull request #402

### PR DESCRIPTION
**Pull request by kcoderhtml**
Added some more parity with the website and some changes to make it easier to read.
Closes #401
Closes #37 
Co-authored-by:  James Munger @bajuba

### CODE REVIEW

**Comment by kcoderhtml** [comment]
Sure also am adding fixes from #37

**Comment by bugadani** [comment]
Alright, looks good, thanks!

A few pro tips:
 - if you write "Closes #401" in the PR description, mergint the pull request will automatically close the issue.
 - usually, if I take someone else's changes (like in this case, parts of #37), I like to mark them as a co-author. It's probably not a big deal, but I think it's nice to do.

**Review by bugadani — APPROVED** [review]

**Comment by kcoderhtml** [comment]
Okay, how would you mark someone as a co-author? I'm fairly new at this.

**Comment by bugadani** [comment]
Usually, you write `Co-authored-by: name <name@example.com>` as the last line of your commit message.

**Comment by kcoderhtml** [comment]
Thank you I will do that!

**Comment by kcoderhtml** [comment]
Thanks!

**Pull request merged**
