### PR TITLE
Icon themes

### PR DESCRIPTION
**Pull request by panekj**
Fixes https://github.com/lapce/lapce/issues/860
Fixes https://github.com/lapce/lapce/issues/1451

### CODE REVIEW

**Comment by dzhou121** [comment]
What's left to do for this? Anything I can do to help.

**Comment by panekj** [comment]
I have not done much since last time we discussed this on discord

**Comment by panekj** [comment]
Moved `VERSION`, `NAME`, `RELEASE` and `Directory` into `lapce-core` as it will be later necessary for implementing lazy-loading tree-sitter grammars
Also fixed re-exporting those static's to just import them everywhere since it's now in lapce-core

**Comment by panekj** [comment]
sorry, didn't noticed it still failed

**Pull request merged**
