### PR TITLE
Run fmt on PRs

### PR DESCRIPTION
**Pull request by tormeh**
Issue: https://github.com/lapce/lapce/issues/483

### CODE REVIEW

**Comment by bugadani** [comment]
I didn't notice, but next time please include "Fixes #483" (or the relevant issue) in the PR description, please. Merging the PR will automatically close the related issue that way. Thank you! :)

**Comment by bugadani** [comment]
This PR causes CI runs to fail: https://github.com/lapce/lapce/actions/runs/2305556842

I think you have to manually run the `cargo fmt --all --  --check` command instead.

**Comment by tormeh** [comment]
> This PR causes CI runs to fail: https://github.com/lapce/lapce/actions/runs/2305556842
> 
> I think you have to manually run the `cargo fmt --all -- --check` command instead.

Ah, sorry guys :( It's tricky to test Github Actions when you're not a privileged contributor somehow

**Comment by bugadani** [comment]
I think I explained a way on discord :) No matter, things will get sorted out eventually. Do you want me to try and fix this?

**Comment by bugadani** [comment]
I think we just did not pay attention: the PR failed with this one: https://github.com/lapce/lapce/actions/runs/2295573043
Anyway, nothing bad happened, so no worries :)

**Pull request merged**
