### PR TITLE
add vue highlight support

### PR DESCRIPTION
**Pull request by xiaoxin-sky**
Hi, I'm add the vue syntax highlight. But the script、style tag is wip. I will continue to work to improve it.

### CODE REVIEW

**Comment by bugadani** [comment]
Some of the crate metadata is incorrect - The "repository" on https://crates.io/crates/tree-sitter-vue points at a page that does not exist.

**Comment by xiaoxin-sky** [comment]
> Some of the crate metadata is incorrect - The "repository" on https://crates.io/crates/tree-sitter-vue points at a page that does not exist. Also, please rebase your changes on master, most of the commits should have been merged already I think.

Sorry, I will change. But the [tree-sitter-vue](https://github.com/ikatyang/tree-sitter-vue) repo seems not active, I create a [pr](https://github.com/ikatyang/tree-sitter-vue/pull/18) for tree-sitter-vue in order to support lapce. but the tree-sitter-vue author doesn't seem to maintain. So, which repo does I write in the repository of crate metadata？The  
Of the original author repository [repository](https://github.com/ikatyang/tree-sitter-vue) or [my repo](https://github.com/xiaoxin-sky/tree-sitter-vue) for the  original author?

**Comment by xiaoxin-sky** [comment]
I have modified the metadata of the repository.

**Review by bugadani — APPROVED** [review]
I'm not sure why the druid dependency was reformatted but no need to delay this PR on that, I think.

**Pull request merged**
