### PR TITLE
Add queries for the `just` language

### PR DESCRIPTION
**Pull request by tgross35**
- [x] Added an entry to `CHANGELOG.md` if this change could be valuable to users

This adds the `just` language, as described at: https://github.com/casey/just. I just used the queries from https://github.com/IndianBoy42/tree-sitter-just/tree/main/queries-flavored/lapce which are currently identical to those for `helix`, but can be adjusted as needed.

However, I can't figure out how to test this. Running `cargo run` and opening a `justfile` doesn't add highlighting, so there must be something missing.

### CODE REVIEW

**Comment by tgross35** [comment]
Is there any tracking issue for being able to add new syntax highlighting as a plugin?

**Comment by panekj** [comment]
Could you update the PR to include only queries and language definition? Grammar will be added to https://github.com/lapce/tree-sitter-grammars by me

**Comment by dzhou121** [comment]
@tgross35 Just tree sitter is now built in https://github.com/lapce/tree-sitter-grammars and is now available on latest v0.4.1 of Lapce. Can you please test if it's working now?

**Comment by tgross35** [comment]
Ah! I'm sorry all, forgot to get back to this one. Thanks for completing it, I'll close this since it is no longer useful.

However, I am on 0.4.1 and still don't seem to be getting the highlighting (tested with both a `justfile` and a `*.just` file). There isn't a separate plugin needed, is there?

**Comment by dzhou121** [comment]
It didn't have the language configuration for `just`, just fixed it by 7c3405c147f18a29f944f51ae00ed9b24b5c1859

**Comment by tgross35** [comment]
Awesome, thanks for the follow up!

**Pull request closed without merging**
