### PR TITLE
Added vims paste before 'P'

### PR DESCRIPTION
**Pull request by LukaOber**
`P` behaves like `p` but instead of inserting after the cursor `P` inserts before the cursor. `P` moves the cursor one to the left before pasting. This move does not occur if the cursor is at the beginning of the line and therefore behaves like vims `P`.

### CODE REVIEW

**Comment by LukaOber** [comment]
The unsuccessful check was due to a network error. It has nothing to do with the added code.

**Comment by MinusGix** [comment]
> The unsuccessful check was due to a network error. It has nothing to do with the added code.

Thanks for mentioning it; I told the check to re-run.

**Comment by LukaOber** [comment]
Sorry for reopening this. I forgot about this PR and deleted my head repository. Is there anything holding this PR back or did it just go under? @MinusGix

**Comment by panekj** [comment]
It's waiting for @dzhou121 to review it

**Comment by erf** [comment]
With this fix, if the cursor is at the beginning of the line it pastes after the first char. It think it should paste at the very beginning of the line. That is how it works in `vim`.

**Comment by LukaOber** [comment]
Okay, I will fix this later today or on the weekend.

**Pull request merged**
