### PR TITLE
fix(editor): filter unnecessary  completion request

### PR DESCRIPTION
**Pull request by xiaoxin-sky**
see #1740 , I don't think empty string requests should be sent when the input has a value. Empty requests can cause language server performance problems.
I test typescript plugin and lapce-vue plugin(base tsserver).

### CODE REVIEW

**Comment by dzhou121** [comment]
The reason we send empty string requests, is to kind of "cache" the completion results locally, so that for the same completion, we can quickly filter locally.

**Comment by xiaoxin-sky** [comment]
> The reason we send empty string requests, is to kind of "cache" the completion results locally, so that for the same completion, we can quickly filter locally.

I think my commit  are not break the cache logic. the cache can work well.
image

**Comment by dzhou121** [comment]
2 requests with one empty string, and the other one with the current input is by design. The empty string request gets all the possible completions which acts as cache. The request with input is for scenarios like auto import in rust-analyzer kicks in only with some input.

**Comment by xiaoxin-sky** [comment]
yeah，I know your thoughts，But every type char  aways send the empty request，this aways lead to the language server calc the almost the same  result. and always slow down the complete.

Can we make an empty request when opening a new file instead of sending an empty request every time we type a char？

**Comment by dzhou121** [comment]
We should do empty request once
https://github.com/lapce/lapce/blob/master/lapce-data/src/editor.rs#L769

One thing that can happen is the response is slow to come back, and we will keep sending the empty requests again and again until we got the response. The way to solve it is to insert a empty Vec for the empty request when we do it.

**Comment by xiaoxin-sky** [comment]
> We should do empty request once https://github.com/lapce/lapce/blob/master/lapce-data/src/editor.rs#L769
> 

Please forgive me for not understanding. Dose [the 769 len](https://github.com/lapce/lapce/blob/master/lapce-data/src/editor.rs#L769) cached global response complete list being used again? Which situation will hit the empty response cache?

In my opinion, First hit the cache must in `CompletionStatus::Started` status, so In this case, the user should be in the state of continuously typing characters or deleting characters,right? 
1. And then if user in the state of continuously typing characters(such as: `abcd`), In my commit ,when user input the second char, it will send empty request, and also send input request('ab'), and then the empty string response will be cached in `input_items`, and the input string also be cached, and user continuously typing the 3rd char,  Because `completion.input_items.contains_key` need to match the full key, so the  `input_items`  can't match 3rd typing('abc'), so need send completion request.  So the response of the empty string in the process is almost hard to hit. 
 2. if user start delete typed chars, Because in the first case，the 'a'、'ab'、'abc' input  had been cached. so it alse not hit empty response.

In the above instructions, assume that the response speed is normal. So It's hard for me to understand that global caching is of great use here. 

> One thing that can happen is the response is slow to come back, and we will keep sending the empty requests again and again until we got the response. 

Of course, the response results did not return in time is another need to solve a problem.

**Comment by dzhou121** [comment]
> In the above instructions, assume that the response speed is normal. So It's hard for me to understand that global caching is of great use here.

The global cache is to display completion results before the response for new input comes back.

**Comment by xiaoxin-sky** [comment]
> The global cache is to display completion results before the response for new input comes back.
>
oh!,I know your design idea. Can I understand that the global is always obtained before each input, and a global list of completion will be displayed before the real content of the input response is returned?
If I understand correctly, then I don't think this is a good idea. On the contrary, the effect is somewhat bad. Because the language need response 2 request，and this will black the 2td request.

**Comment by dzhou121** [comment]
I think the real issue is that we keep sending the requests until the response is back. I'll fix that and you can test if it solves the problem.

**Comment by xiaoxin-sky** [comment]
Ok, I continue to follow your updates. 🚀😄

**Comment by dzhou121** [comment]
Can you please see if https://github.com/lapce/lapce/pull/1746 fixes the issue?

**Comment by xiaoxin-sky** [comment]
> Can you please see if #1746 fixes the issue?

I can see the continuous input and Competion pop-up window will no longer flash.nice. It's kind of a repair.
Although the first empty request can not be removed for design reasons. But better than before

**Comment by xiaoxin-sky** [comment]
I close the pr.

**Pull request closed without merging**
